In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pyarrow

In [2]:
print("Project Started")

Project Started

Step1:- create var project dir and store csv data path

In [3]:
PROJECT_DIR = Path(
    r"C:\Users\Yaseen\DA_DS\MINI_PROJECT\smart_data_analysis\data"
)

In [4]:
DATA_DIR = PROJECT_DIR

Step2:- create two more var sales and inventory or this var store csv file then print csv file

In [5]:
sales = pd.read_csv(DATA_DIR / "retail_sales_ml_apl.csv")

In [6]:
inventory = pd.read_csv(DATA_DIR / "retail_inventory_ml_apl.csv")

In [7]:
print("Sales Shape:", sales.shape)
print("Inventory Shape:", inventory.shape)

Sales Shape: (125751, 17)
Inventory Shape: (284755, 18)

In [8]:
display(sales.head())

,Transaction Date,Sales Type,Is Return,Reason of Return,Supplier,Product No,Product Description,Product Division,Product Category,Product Subcategory,Product Segment,Store,Sales Channel,Qty Sold,Sales Amount,Cogs,Number of Transactions
0,2025-09-01,Full Price,0,NaN,Vendor 0169,PROD-139867,PROD-100449 SEG-500065 Scholar Footwear Trailb...,Scholar Footwear,Scholar Footwear Trailblazer,Scholar Footwear Trailblazer Equilibrium,SEG-500065 Scholar Footwear Trailblazer Equili...,STR-1006,Channel Alpha,1.0,115.00,52.31,1
1,2025-09-07,Full Price,0,NaN,Vendor 0166,PROD-100449,PROD-100825 SEG-500112 Heritage Footwear Fligh...,Femme Footwear,Femme Footwear Flight Classic,Femme Footwear Flight Classic Varied,SEG-500112 Heritage Footwear Flight Classic Ze...,STR-1198,Channel Alpha,1.0,115.00,58.47,1
2,2025-08-06,Promo,0,NaN,Vendor 0169,PROD-153623,PROD-148813 SEG-511388 Scholar Footwear Trailb...,Scholar Footwear,Scholar Footwear Trailblazer,Scholar Footwear Trailblazer Equilibrium,SEG-511388 Scholar Footwear Trailblazer Equili...,STR-1157,Channel Alpha,1.0,79.99,43.76,1
3,2025-08-31,Full Price,0,NaN,Vendor 0246,PROD-140876,PROD-100419 SEG-500063 Scholar Footwear Boot C...,Scholar Footwear,Scholar Footwear Boot Collection,Scholar Footwear Boot Collection Woodland,SEG-500063 Scholar Footwear Boot Collection Wo...,STR-1234,Channel Alpha,1.0,110.00,50.60,1
4,2026-03-22,Full Price,0,NaN,Vendor 0169,PROD-166113,PROD-149345 SEG-511444 Femme Footwear Trailbla...,Femme Footwear,Femme Footwear Trailblazer,Femme Footwear Trailblazer Equilibrium,SEG-511444 Femme Footwear Trailblazer Equilibrium,STR-1157,Channel Alpha,1.0,160.00,77.95,1

In [9]:
display(inventory.head())

,Start Date,End Date,Stock Status,Supplier,Product No,Product Description,Product Division,Product Category,Product Subcategory,Product Segment,Store,Store Type,Sales Channel,Qty on hand,Stocks Selling Amount,Cost of Stocks,Stock Unit Selling Price,Stock Unit Cost Price
0,2025-08-07,2025-10-18,Full Price,Vendor 0255,PROD-159369,PROD-103395 SEG-500461 Scholar Footwear Canvas...,Scholar Footwear,Scholar Footwear Canvas Styles,Scholar Footwear Canvas Styles Drifter,SEG-500461 Scholar Footwear Canvas Styles Drifter,STR-1010,Retail Storefront,Channel Alpha,1,55.0,24.75,55.0,24.75
1,2026-02-15,2026-02-15,Full Price,Vendor 0010,PROD-180713,PROD-190644 SEG-520887 Femme Footwear Court Ca...,Femme Footwear,Femme Footwear Court Casual,Femme Footwear Court Casual Trident,SEG-520887 Femme Footwear Court Casual Trident,STR-1082,Retail Storefront,Channel Alpha,1,130.0,59.73,130.0,59.73
2,2026-01-08,2026-02-15,Full Price,Vendor 0166,PROD-169474,PROD-153439 SEG-512518 Femme Footwear Court Ca...,Femme Footwear,Femme Footwear Court Casual,Femme Footwear Court Casual Zephyr,SEG-512518 Femme Footwear Court Casual Zephyr,STR-1105,Retail Storefront,Channel Alpha,1,120.0,60.44,120.0,60.44
3,2025-12-23,2026-02-15,Full Price,Vendor 0106,PROD-170976,PROD-122029 SEG-504463 Junior Apparel Cozy Pul...,Junior Apparel,Junior Apparel Cozy Pullovers,Junior Apparel Cozy Pullovers Varied,SEG-504463 Junior Apparel Cozy Pullovers Varied,STR-1157,Retail Storefront,Channel Alpha,3,150.0,52.50,50.0,17.50
4,2026-02-10,9999-12-31,Full Price,Vendor 0134,PROD-183525,PROD-111954 SEG-502325 Scholar Footwear Modern...,Scholar Footwear,Scholar Footwear Modern Legend,Scholar Footwear Modern Legend Summit,SEG-502325 Scholar Footwear Modern Legend Summit,STR-1253,Retail Storefront,Channel Alpha,4,360.0,182.16,90.0,45.54

In [10]:
print(sales.info())
print(inventory.info())

<class 'pandas.DataFrame'>
RangeIndex: 125751 entries, 0 to 125750
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Transaction Date        125751 non-null  str
 1   Sales Type              125751 non-null  str
 2   Is Return               125751 non-null  int64
 3   Reason of Return        0 non-null       float64
 4   Supplier                125751 non-null  str
 5   Product No              125751 non-null  str
 6   Product Description     125751 non-null  str
 7   Product Division        125751 non-null  str
 8   Product Category        125751 non-null  str
 9   Product Subcategory     125751 non-null  str
 10  Product Segment         125751 non-null  str
 11  Store                   125751 non-null  str
 12  Sales Channel           125751 non-null  str
 13  Qty Sold                125751 non-null  float64
 14  Sales Amount            125751 non-null  float64
 15  Cogs                    125751 non-null  float64
 16  Number of Transactions  125751 non-null  int64
dtypes: float64(4), int64(2), str(11)
memory usage: 46.2 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 284755 entries, 0 to 284754
Data columns (total 18 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Start Date                284755 non-null  str
 1   End Date                  284755 non-null  str
 2   Stock Status              284755 non-null  str
 3   Supplier                  284755 non-null  str
 4   Product No                284755 non-null  str
 5   Product Description       284755 non-null  str
 6   Product Division          284755 non-null  str
 7   Product Category          284755 non-null  str
 8   Product Subcategory       284755 non-null  str
 9   Product Segment           284755 non-null  str
 10  Store                     284755 non-null  str
 11  Store Type                284755 non-null  str
 12  Sales Channel             284755 non-null  str
 13  Qty on hand               284755 non-null  int64
 14  Stocks Selling Amount     284755 non-null  float64
 15  Cost of Stocks            284755 non-null  float64
 16  Stock Unit Selling Price  284755 non-null  float64
 17  Stock Unit Cost Price     284755 non-null  float64
dtypes: float64(4), int64(1), str(13)
memory usage: 114.2 MB
None

Step4:-Data Audit (means analysis start karne se pehle data ki condition check karna.  
1)Data mein kitni rows aur columns hain?  
2)Koi information missing toh nahi?  
3)Koi records duplicate toh nahi?  
4)Dates aur numbers correct data types mein hain ya nahi?)

In [11]:
print("Shape:", sales.shape)

Shape: (125751, 17)

In [12]:
print(sales.isnull().sum())

Transaction Date               0
Sales Type                     0
Is Return                      0
Reason of Return          125751
Supplier                       0
Product No                     0
Product Description            0
Product Division               0
Product Category               0
Product Subcategory            0
Product Segment                0
Store                          0
Sales Channel                  0
Qty Sold                       0
Sales Amount                   0
Cogs                           0
Number of Transactions         0
dtype: int64

In [13]:
print("Duplicate rowa: ",sales.duplicated().sum())

Duplicate rowa:  0

Sales aur inventory alag business questions answer karte hain.  
sales	:-> Kaunsa product kitna sell hua aur kitna revenue aaya?  
inventory	:-> Kitna stock available hai aur uski value kitni hai?

In [14]:
print("\nINVENTORY MISSING VALUES")
print(inventory.isnull().sum())

INVENTORY MISSING VALUES
Start Date                  0
End Date                    0
Stock Status                0
Supplier                    0
Product No                  0
Product Description         0
Product Division            0
Product Category            0
Product Subcategory         0
Product Segment             0
Store                       0
Store Type                  0
Sales Channel               0
Qty on hand                 0
Stocks Selling Amount       0
Cost of Stocks              0
Stock Unit Selling Price    0
Stock Unit Cost Price       0
dtype: int64

In [15]:
print("\nINVENTORY DUPLICATES")
print(inventory.duplicated().sum())

INVENTORY DUPLICATES
0

Step 5 — Business data inspect karo  
Is step ka purpose hai dataset ke andar ka actual data dekhna, taaki humein pata chale ki values sensible hain ya nahi.

In [16]:
display(sales.sample(5, random_state=42))

,Transaction Date,Sales Type,Is Return,Reason of Return,Supplier,Product No,Product Description,Product Division,Product Category,Product Subcategory,Product Segment,Store,Sales Channel,Qty Sold,Sales Amount,Cogs,Number of Transactions
16615,2025-12-07,Promo,0,NaN,Vendor 0169,PROD-166166,PROD-148939 SEG-511404 Femme Footwear Trailbla...,Femme Footwear,Femme Footwear Trailblazer,Femme Footwear Trailblazer Equilibrium,SEG-511404 Femme Footwear Trailblazer Equilibrium,STR-1074,Channel Alpha,1.0,59.99,50.05,1
98454,2025-09-01,Full Price,0,NaN,Vendor 0166,PROD-168840,PROD-170351 SEG-516327 Junior Apparel Crew Tee...,Junior Apparel,Junior Apparel Crew Tees,Junior Apparel Crew Tees Varied,SEG-516327 Junior Apparel Crew Tees Varied,STR-1114,Channel Alpha,1.0,25.00,11.50,1
120727,2025-12-06,Full Price,0,NaN,Vendor 0258,PROD-184465,PROD-179900 SEG-518118 Scholar Footwear Trailb...,Scholar Footwear,Scholar Footwear Trailblazer,Scholar Footwear Trailblazer Swift Run,SEG-518118 Scholar Footwear Trailblazer Swift Run,STR-1344,Channel Alpha,1.0,49.50,43.56,1
45753,2025-06-30,Promo,0,NaN,Vendor 0010,PROD-157528,PROD-122574 SEG-504599 Femme Footwear Court Ca...,Femme Footwear,Femme Footwear Court Casual,Femme Footwear Court Casual Trident,SEG-504599 Femme Footwear Court Casual Trident,STR-1157,Channel Alpha,1.0,59.99,51.70,1
106261,2025-06-27,Full Price,0,NaN,Vendor 0166,PROD-161780,PROD-188025 SEG-520261 Femme Footwear Trailbla...,Femme Footwear,Femme Footwear Trailblazer,Femme Footwear Trailblazer Zephyr,SEG-520261 Femme Footwear Trailblazer Zephyr,STR-1148,Channel Alpha,1.0,90.00,45.04,1

In [17]:
display(inventory.sample(5, random_state=42))

,Start Date,End Date,Stock Status,Supplier,Product No,Product Description,Product Division,Product Category,Product Subcategory,Product Segment,Store,Store Type,Sales Channel,Qty on hand,Stocks Selling Amount,Cost of Stocks,Stock Unit Selling Price,Stock Unit Cost Price
15276,2025-11-19,2026-02-06,Full Price,Vendor 0134,PROD-170321,PROD-113872 SEG-502503 Scholar Footwear Retro ...,Scholar Footwear,Scholar Footwear Retro Legend,Scholar Footwear Retro Legend Summit,SEG-502503 Scholar Footwear Retro Legend Summit,STR-1044,Retail Storefront,Channel Alpha,1,160.00,80.96,160.00,80.960
211523,2026-03-10,2026-04-06,Markdown Tier 2,Vendor 0106,PROD-158966,PROD-168071 SEG-515903 Junior Apparel Crop Pan...,Junior Apparel,Junior Apparel Crop Pants,Junior Apparel Crop Pants Varied,SEG-515903 Junior Apparel Crop Pants Varied,STR-1109,Retail Storefront,Channel Alpha,1,14.99,12.25,14.99,12.250
185693,2025-07-09,2025-07-17,Full Price,Vendor 0166,PROD-169448,PROD-173856 SEG-516960 Femme Footwear Flight C...,Femme Footwear,Femme Footwear Flight Classic,Femme Footwear Flight Classic Varied,SEG-516960 Femme Footwear Flight Classic Varied,STR-1105,Retail Storefront,Channel Alpha,1,115.00,58.19,115.00,58.190
237329,2026-01-12,2026-01-22,Full Price,Vendor 0106,PROD-190339,PROD-137214 SEG-508422 Junior Apparel Crew Tee...,Junior Apparel,Junior Apparel Crew Tees,Junior Apparel Crew Tees Varied,SEG-508422 Junior Apparel Crew Tees Varied,STR-1237,Retail Storefront,Channel Alpha,4,112.00,33.60,28.00,8.400
278500,2025-10-17,2025-11-13,Full Price,Vendor 0169,PROD-152224,PROD-149105 SEG-511422 Scholar Footwear Trailb...,Scholar Footwear,Scholar Footwear Trailblazer,Scholar Footwear Trailblazer Equilibrium,SEG-511422 Scholar Footwear Trailblazer Equili...,STR-1094,Retail Storefront,Channel Alpha,2,180.00,83.07,90.00,41.535

Step 6:- Data quality report

In [18]:
print("SALES SHAPE :", sales.shape)
print("\nSALES MISSING VALUES")
print(sales.isnull().sum())

SALES SHAPE : (125751, 17)

SALES MISSING VALUES
Transaction Date               0
Sales Type                     0
Is Return                      0
Reason of Return          125751
Supplier                       0
Product No                     0
Product Description            0
Product Division               0
Product Category               0
Product Subcategory            0
Product Segment                0
Store                          0
Sales Channel                  0
Qty Sold                       0
Sales Amount                   0
Cogs                           0
Number of Transactions         0
dtype: int64

In [19]:
print("\nSALES DUPLICATES :", sales.duplicated().sum())

SALES DUPLICATES : 0

In [20]:
print("\nRETURN COUNTS")
print(sales["Is Return"].value_counts(dropna=False))

RETURN COUNTS
Is Return
0    118260
1      7491
Name: count, dtype: int64

In [21]:
print("\nQUANITITY SUMMARY")
print(sales["Qty Sold"].describe())

QUANITITY SUMMARY
count    125751.000000
mean          0.930370
std           0.586897
min          -3.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          14.000000
Name: Qty Sold, dtype: float64

In [22]:
# Negative values investigate 
return_quantity_check = (
    sales.groupby("Is Return")["Qty Sold"].agg(["count", "min", "max", "mean"])
)
display(return_quantity_check)

            count  min   max      mean
Is Return
0          118260  0.0  14.0  1.053120
1            7491 -3.0  -1.0 -1.007476

In [23]:
negative_sales = sales[sales["Qty Sold"] < 0]
print("Negative quantity records: ", len(negative_sales))

Negative quantity records:  7491

In [24]:
display(
    negative_sales[
        ["Transaction Date", "Is Return", "Product No", "Qty Sold", "Sales Amount", "Cogs"]
    ].head(10)
)

    Transaction Date  Is Return   Product No  Qty Sold  Sales Amount   Cogs
39        2026-03-14          1  PROD-183451      -1.0       -165.00 -83.49
47        2025-07-30          1  PROD-144341      -1.0        -69.99 -50.05
68        2026-03-14          1  PROD-188440      -1.0        -60.00 -23.40
115       2025-12-29          1  PROD-152224      -1.0        -63.00 -38.67
151       2025-08-23          1  PROD-160814      -1.0       -120.00 -60.06
153       2025-08-28          1  PROD-143184      -1.0       -110.00 -50.05
162       2026-01-02          1  PROD-100813      -1.0        -90.00 -45.51
168       2025-12-24          1  PROD-100043      -1.0       -112.00 -67.99
190       2025-09-14          1  PROD-167815      -1.0       -110.00 -55.66
200       2025-12-10          1  PROD-176331      -1.0        -81.00 -45.54

In [25]:
print("\nINVENTORY MISSING VALUES")
print(inventory.isnull().sum())

INVENTORY MISSING VALUES
Start Date                  0
End Date                    0
Stock Status                0
Supplier                    0
Product No                  0
Product Description         0
Product Division            0
Product Category            0
Product Subcategory         0
Product Segment             0
Store                       0
Store Type                  0
Sales Channel               0
Qty on hand                 0
Stocks Selling Amount       0
Cost of Stocks              0
Stock Unit Selling Price    0
Stock Unit Cost Price       0
dtype: int64

In [26]:
print("\nINVENTORY DUPLICATES:", inventory.duplicated().sum())

INVENTORY DUPLICATES: 0

In [27]:
print("\nSTOCK SUMMARY")
print(inventory["Qty on hand"].describe())

STOCK SUMMARY
count    284755.000000
mean          2.294629
std           2.007395
min          -9.000000
25%           1.000000
50%           2.000000
75%           3.000000
max          56.000000
Name: Qty on hand, dtype: float64

In [28]:
# inventoryu negative value investigate
negative_stock = inventory[inventory["Qty on hand"] < 0]
print("Negative stock records: ", len(negative_stock))

Negative stock records:  1380

In [29]:
display(
    negative_stock[
         ["Start Date", "End Date", "Stock Status",
         "Product No", "Product Description",
         "Store", "Qty on hand", "Cost of Stocks"]
    ].head(10)
)

,Start Date,End Date,Stock Status,Product No,Product Description,Store,Qty on hand,Cost of Stocks
11,2025-09-06,2026-01-05,Full Price,PROD-100353,PROD-164489 SEG-515310 Femme Footwear Court Ca...,STR-1145,-1,-59.17
298,2025-10-28,2026-01-04,Markdown Tier 2,PROD-148307,PROD-117613 SEG-503080 Junior Apparel Printed ...,STR-1157,-2,-14.50
463,2025-10-26,2025-10-26,Markdown Tier 2,PROD-139506,PROD-118198 SEG-503268 Scholar Footwear Retro ...,STR-1163,-1,-70.07
1059,2026-03-14,9999-12-31,Markdown Tier 2,PROD-161861,PROD-170262 SEG-516305 Junior Apparel Trousers...,STR-1107,-1,-15.92
1372,2026-03-04,2026-03-04,Full Price,PROD-175050,PROD-166383 SEG-515621 Scholar Footwear Trailb...,STR-1222,-1,-74.38
1769,2026-04-05,2026-04-09,Markdown Tier 1,PROD-153852,PROD-134075 SEG-507544 Junior Apparel Miscella...,STR-1198,-1,-23.50
2203,2025-12-19,2026-01-05,Full Price,PROD-163861,PROD-180137 SEG-518154 Femme Footwear Trailbla...,STR-1010,-2,-99.16
2246,2025-06-25,2025-12-07,Full Price,PROD-152547,PROD-128745 SEG-506280 Femme Footwear Court Ca...,STR-1044,-1,-67.58
2708,2026-01-05,2026-01-06,Full Price,PROD-124596,PROD-100991 SEG-500125 Toddler Footwear Flight...,STR-1038,-1,-40.45
2711,2025-11-14,2026-01-06,Full Price,PROD-152045,PROD-166020 SEG-515561 Scholar Footwear Modern...,STR-1044,-1,-55.09

In [30]:
sales["Transaction Date"] = pd.to_datetime(
    sales["Transaction Date"], errors="coerce"
)

In [31]:
print("Sales start date:", sales["Transaction Date"].min())
print("Sales end date:", sales["Transaction Date"].max())
print(
    "Invalid sales dates:",
    sales["Transaction Date"].isna().sum()
)

Sales start date: 2025-06-01 00:00:00
Sales end date: 2026-04-24 00:00:00
Invalid sales dates: 0

In [32]:
# 2. Inventory date range
inventory["Start Date"] = pd.to_datetime(
    inventory["Start Date"],
    errors="coerce"
)

inventory["End Date"] = pd.to_datetime(
    inventory["End Date"],
    errors="coerce"
)

In [33]:
print("\nInventory start date:", inventory["Start Date"].min())
print("Inventory end date:", inventory["End Date"].max())

print(
    "Invalid inventory start dates:",
    inventory["Start Date"].isna().sum()
)

print(
    "Invalid inventory end dates:",
    inventory["End Date"].isna().sum()
)

Inventory start date: 2025-06-01 00:00:00
Inventory end date: 9999-12-31 00:00:00
Invalid inventory start dates: 0
Invalid inventory end dates: 0

In [34]:
# 3. Stock status
print("\nStock status counts:")
display(inventory["Stock Status"].value_counts(dropna=False))

Stock status counts:

Stock Status
Full Price         261899
Markdown Tier 1     12091
Markdown Tier 2      6937
Clearance            3798
Promo                  30
Name: count, dtype: int64

In [35]:
# 4. Negative stock by status
print("\nNegative stock by status:")
display(
    inventory[inventory["Qty on hand"] < 0]
    .groupby("Stock Status")
    .agg(
        records=("Qty on hand", "size"),
        total_quantity=("Qty on hand", "sum")
    )
    .sort_values("records", ascending=False)
)

Negative stock by status:

                 records  total_quantity
Stock Status
Full Price          1078           -1385
Markdown Tier 1      161            -201
Markdown Tier 2       81            -101
Clearance             60             -80

In [36]:
negative_stock = inventory[
    inventory["Qty on hand"] < 0
]

In [37]:
# Most affected products
print("Top 10 products with negative stock:")

display(
    negative_stock.groupby(
        ["Product No", "Product Description"]
    )
    .agg(
        negative_records=("Qty on hand", "size"),
        total_stock=("Qty on hand", "sum")
    )
    .sort_values("negative_records", ascending=False)
    .head(10)
)

Top 10 products with negative stock:

,,negative_records,total_stock
Product No,Product Description,,
PROD-161865,PROD-101708 SEG-500224 Scholar Footwear Sandals Varied,58,-120
PROD-161863,PROD-101706 SEG-500224 Scholar Footwear Sandals Varied,22,-34
PROD-161864,PROD-101707 SEG-500224 Scholar Footwear Sandals Varied,22,-45
PROD-154121,PROD-179746 SEG-518093 Femme Footwear Court Casual Trident,16,-17
PROD-154123,PROD-179748 SEG-518093 Femme Footwear Court Casual Trident,12,-12
PROD-163861,PROD-180137 SEG-518154 Femme Footwear Trailblazer Swift Run,12,-17
PROD-154122,PROD-179747 SEG-518093 Femme Footwear Court Casual Trident,10,-10
PROD-121534,PROD-102950 SEG-500406 Scholar Footwear Court Casual Trident,10,-21
PROD-166230,PROD-149558 SEG-511488 Junior Apparel Cozy Pullovers Varied,10,-10
PROD-166363,PROD-102541 SEG-500347 Scholar Footwear Trailblazer Equilibrium,10,-10

In [38]:
# Most affected stores
print("Top 10 stores with negative stock:")

display(
    negative_stock.groupby("Store")
    .agg(
        negative_records=("Qty on hand", "size"),
        total_stock=("Qty on hand", "sum")
    )
    .sort_values("negative_records", ascending=False)
    .head(10)
)

Top 10 stores with negative stock:

          negative_records  total_stock
Store
STR-1198                96         -115
STR-1157                81         -168
STR-1255                72          -95
STR-1044                69          -80
STR-1222                69          -82
STR-1085                60          -66
STR-1010                53          -78
STR-1163                52          -52
STR-1006                48          -66
STR-1194                46          -54

In [39]:
# Negative stock value check
print("Negative stock quantity:", (inventory["Qty on hand"] < 0).sum())

print(
    "Negative cost of stocks:",
    (inventory["Cost of Stocks"] < 0).sum()
)

print(
    "Negative stock selling amount:",
    (inventory["Stocks Selling Amount"] < 0).sum()
)

Negative stock quantity: 1380
Negative cost of stocks: 8022
Negative stock selling amount: 1380

In [40]:
# Return transaction summary
return_summary = (
    sales.groupby("Is Return")
    .agg(
        records=("Is Return", "size"),
        quantity=("Qty Sold", "sum"),
        sales_amount=("Sales Amount", "sum"),
        cogs=("Cogs", "sum")
    )
)

display(return_summary)

           records  quantity  sales_amount          cogs
Is Return
0           118260  124542.0   11215681.26  6.255527e+06
1             7491   -7547.0    -733571.01 -4.077757e+05

In [41]:
%pip install pyarrow

Requirement already satisfied: pyarrow in c:\Users\Yaseen\DA_DS\MINI_PROJECT\smart_data_analysis\.venv\Lib\site-packages (26.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [42]:
print("PyArrow version:", pyarrow.__version__)

PyArrow version: 26.0.0

In [43]:
PROJECT_DIR = Path(
    r"C:\Users\Yaseen\DA_DS\MINI_PROJECT\smart_data_analysis"
)

PROCESSED_DIR = PROJECT_DIR / "processed_data"
PROCESSED_DIR.mkdir(exist_ok=True)

sales.to_parquet(
    PROCESSED_DIR / "sales_audit.parquet",
    index=False
)

inventory.to_parquet(
    PROCESSED_DIR / "inventory_audit.parquet",
    index=False
)

print("Both files exported successfully!")

Both files exported successfully!

In [44]:
print(list(PROCESSED_DIR.glob("*.parquet")))

[WindowsPath('C:/Users/Yaseen/DA_DS/MINI_PROJECT/smart_data_analysis/processed_data/inventory_audit.parquet'), WindowsPath('C:/Users/Yaseen/DA_DS/MINI_PROJECT/smart_data_analysis/processed_data/sales_audit.parquet')]