# Exploratory Data Analysis (EDA)

This notebook explores retail sales and inventory data to identify business trends, product performance, return patterns, and potential inventory risks.

The analysis uses the cleaned Parquet datasets prepared in the data cleaning phase.

In [2]:
# step 9.1 — Load Cleaned datasets

In [3]:
from pathlib import Path
import pandas as pd
import numpy as np

In [4]:
PROJECT_DIR = Path(
    r"C:\Users\Yaseen\DA_DS\MINI_PROJECT\smart_data_analysis"
)

PROCESSED_DIR = PROJECT_DIR / "processed_data"

In [5]:
sales = pd.read_parquet(
    PROCESSED_DIR / "sales_clean.parquet"
)

inventory = pd.read_parquet(
    PROCESSED_DIR / "inventory_clean.parquet"
)

In [6]:
print("Sales dataset shape:", sales.shape)
print("Inventory dataset shape:", inventory.shape)

Sales dataset shape: (125751, 16)
Inventory dataset shape: (284755, 21)

In [7]:
display(sales.head())
display(inventory.head())

,Transaction Date,Sales Type,Is Return,Supplier,Product No,Product Description,Product Division,Product Category,Product Subcategory,Product Segment,Store,Sales Channel,Qty Sold,Sales Amount,Cogs,Number of Transactions
0,2025-09-01,Full Price,0,Vendor 0169,PROD-139867,PROD-100449 SEG-500065 Scholar Footwear Trailb...,Scholar Footwear,Scholar Footwear Trailblazer,Scholar Footwear Trailblazer Equilibrium,SEG-500065 Scholar Footwear Trailblazer Equili...,STR-1006,Channel Alpha,1.0,115.00,52.31,1
1,2025-09-07,Full Price,0,Vendor 0166,PROD-100449,PROD-100825 SEG-500112 Heritage Footwear Fligh...,Femme Footwear,Femme Footwear Flight Classic,Femme Footwear Flight Classic Varied,SEG-500112 Heritage Footwear Flight Classic Ze...,STR-1198,Channel Alpha,1.0,115.00,58.47,1
2,2025-08-06,Promo,0,Vendor 0169,PROD-153623,PROD-148813 SEG-511388 Scholar Footwear Trailb...,Scholar Footwear,Scholar Footwear Trailblazer,Scholar Footwear Trailblazer Equilibrium,SEG-511388 Scholar Footwear Trailblazer Equili...,STR-1157,Channel Alpha,1.0,79.99,43.76,1
3,2025-08-31,Full Price,0,Vendor 0246,PROD-140876,PROD-100419 SEG-500063 Scholar Footwear Boot C...,Scholar Footwear,Scholar Footwear Boot Collection,Scholar Footwear Boot Collection Woodland,SEG-500063 Scholar Footwear Boot Collection Wo...,STR-1234,Channel Alpha,1.0,110.00,50.60,1
4,2026-03-22,Full Price,0,Vendor 0169,PROD-166113,PROD-149345 SEG-511444 Femme Footwear Trailbla...,Femme Footwear,Femme Footwear Trailblazer,Femme Footwear Trailblazer Equilibrium,SEG-511444 Femme Footwear Trailblazer Equilibrium,STR-1157,Channel Alpha,1.0,160.00,77.95,1

,Start Date,End Date,Stock Status,Supplier,Product No,Product Description,Product Division,Product Category,Product Subcategory,Product Segment,...,Store Type,Sales Channel,Qty on hand,Stocks Selling Amount,Cost of Stocks,Stock Unit Selling Price,Stock Unit Cost Price,Negative_Quantity_Flag,Negative_Cost_Flag,Negative_Quantity_And_Cost_Flag
0,2025-08-07,2025-10-18,Full Price,Vendor 0255,PROD-159369,PROD-103395 SEG-500461 Scholar Footwear Canvas...,Scholar Footwear,Scholar Footwear Canvas Styles,Scholar Footwear Canvas Styles Drifter,SEG-500461 Scholar Footwear Canvas Styles Drifter,...,Retail Storefront,Channel Alpha,1,55.0,24.75,55.0,24.75,False,False,False
1,2026-02-15,2026-02-15,Full Price,Vendor 0010,PROD-180713,PROD-190644 SEG-520887 Femme Footwear Court Ca...,Femme Footwear,Femme Footwear Court Casual,Femme Footwear Court Casual Trident,SEG-520887 Femme Footwear Court Casual Trident,...,Retail Storefront,Channel Alpha,1,130.0,59.73,130.0,59.73,False,False,False
2,2026-01-08,2026-02-15,Full Price,Vendor 0166,PROD-169474,PROD-153439 SEG-512518 Femme Footwear Court Ca...,Femme Footwear,Femme Footwear Court Casual,Femme Footwear Court Casual Zephyr,SEG-512518 Femme Footwear Court Casual Zephyr,...,Retail Storefront,Channel Alpha,1,120.0,60.44,120.0,60.44,False,False,False
3,2025-12-23,2026-02-15,Full Price,Vendor 0106,PROD-170976,PROD-122029 SEG-504463 Junior Apparel Cozy Pul...,Junior Apparel,Junior Apparel Cozy Pullovers,Junior Apparel Cozy Pullovers Varied,SEG-504463 Junior Apparel Cozy Pullovers Varied,...,Retail Storefront,Channel Alpha,3,150.0,52.50,50.0,17.50,False,False,False
4,2026-02-10,9999-12-31,Full Price,Vendor 0134,PROD-183525,PROD-111954 SEG-502325 Scholar Footwear Modern...,Scholar Footwear,Scholar Footwear Modern Legend,Scholar Footwear Modern Legend Summit,SEG-502325 Scholar Footwear Modern Legend Summit,...,Retail Storefront,Channel Alpha,4,360.0,182.16,90.0,45.54,False,False,False

# STEP 9.2: UNDERSTAND DATA STRUCTURE

In [9]:
print("========== SALES DATA ==========")

sales.info()

========== SALES DATA ==========
<class 'pandas.DataFrame'>
RangeIndex: 125751 entries, 0 to 125750
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Transaction Date        125751 non-null  datetime64[us]
 1   Sales Type              125751 non-null  str
 2   Is Return               125751 non-null  int64
 3   Supplier                125751 non-null  str
 4   Product No              125751 non-null  str
 5   Product Description     125751 non-null  str
 6   Product Division        125751 non-null  str
 7   Product Category        125751 non-null  str
 8   Product Subcategory     125751 non-null  str
 9   Product Segment         125751 non-null  str
 10  Store                   125751 non-null  str
 11  Sales Channel           125751 non-null  str
 12  Qty Sold                125751 non-null  float64
 13  Sales Amount            125751 non-null  float64
 14  Cogs                    125751 non-null  float64
 15  Number of Transactions  125751 non-null  int64
dtypes: datetime64[us](1), float64(3), int64(2), str(10)
memory usage: 44.0 MB

In [10]:
print("\n========== INVENTORY DATA ==========")

inventory.info()

========== INVENTORY DATA ==========
<class 'pandas.DataFrame'>
RangeIndex: 284755 entries, 0 to 284754
Data columns (total 21 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Start Date                       284755 non-null  datetime64[us]
 1   End Date                         284755 non-null  datetime64[us]
 2   Stock Status                     284755 non-null  str
 3   Supplier                         284755 non-null  str
 4   Product No                       284755 non-null  str
 5   Product Description              284755 non-null  str
 6   Product Division                 284755 non-null  str
 7   Product Category                 284755 non-null  str
 8   Product Subcategory              284755 non-null  str
 9   Product Segment                  284755 non-null  str
 10  Store                            284755 non-null  str
 11  Store Type                       284755 non-null  str
 12  Sales Channel                    284755 non-null  str
 13  Qty on hand                      284755 non-null  int64
 14  Stocks Selling Amount            284755 non-null  float64
 15  Cost of Stocks                   284755 non-null  float64
 16  Stock Unit Selling Price         284755 non-null  float64
 17  Stock Unit Cost Price            284755 non-null  float64
 18  Negative_Quantity_Flag           284755 non-null  bool
 19  Negative_Cost_Flag               284755 non-null  bool
 20  Negative_Quantity_And_Cost_Flag  284755 non-null  bool
dtypes: bool(3), datetime64[us](2), float64(4), int64(1), str(11)
memory usage: 109.6 MB

## Step 10 — Overall Sales Performance Analysis

### Step 10.1: Overall Sales Performance

Calculate key sales metrics to understand the overall performance of the retail business, including sales value, quantity sold, return activity, cost of goods sold, and estimated gross profit.

In [11]:
total_records  = len(sales)

In [12]:
# Separate normal sales and return-marked records
normal_sales = sales[sales["Is Return"] == 0]
returns = sales[sales["Is Return"] == 1]

In [17]:
# Calculate overall metrics
total_sales_records = len(normal_sales)
total_return_records = len(returns)

total_sales_amount = normal_sales["Sales Amount"].sum()
total_return_amount = returns["Sales Amount"].sum()

total_qty_sold = normal_sales["Qty Sold"].sum()
total_return_qty = returns["Qty Sold"].sum()

total_cogs = normal_sales["Cogs"].sum()
gross_profit = total_sales_amount - total_cogs

return_recod_percentage = ( total_return_records / total_records) * 100

In [19]:
print("Total sales dataset records:", total_records)
print("Normal sales records:", total_sales_records)
print("Return-marked records:", total_return_records)

print(f"\nNormal sales amount: ₹{total_sales_amount:,.2f}")
print(f"Return amount: ₹{total_return_amount:,.2f}")

print(f"\nQuantity sold: {total_qty_sold:,.0f}")
print(f"Returned quantity: {total_return_qty:,.0f}")

print(f"\nNormal sales COGS: ₹{total_cogs:,.2f}")
print(f"Estimated gross profit: ₹{gross_profit:,.2f}")

print(
    f"\nReturn-marked records: "
    f"{return_recod_percentage:.2f}% of all records"
)

Total sales dataset records: 125751
Normal sales records: 118260
Return-marked records: 7491

Normal sales amount: ₹11,215,681.26
Return amount: ₹-733,571.01

Quantity sold: 124,542
Returned quantity: -7,547

Normal sales COGS: ₹6,255,526.82
Estimated gross profit: ₹4,960,154.44

Return-marked records: 5.96% of all records

## Step 10.2 Monthly Sales Trend
# "Month-wise sales value kaise change hui, aur Kaunse month mein sales sabse zyada thi?"
# Analyze monthly sales value and quantity sold to identify high-performing and low-performing months. Return-marked records are excluded from this initial normal-sales trend and will be analyzed separately.

In [ ]:
# keep normal sales records
monthly_sales_data = sales[sales["Is Return"] == 0].copy()

In [21]:
# Extract month from transaction date
monthly_sales_data["Month"]= (
    monthly_sales_data["Transaction Date"].dt.to_period("M")
)

In [22]:
# Aggregate monthly metrics
monthly_sales = (
    monthly_sales_data
    .groupby("Month")
    .agg(
        Sales_Records=("Sales Amount", "size"),
        Total_Revenue=("Sales Amount", "sum"),
        Total_Quantity=("Qty Sold", "sum"),
        Total_COGS=("Cogs", "sum")
    )
    .reset_index()
)

In [24]:
# Calculate estimated gross profit
monthly_sales["Estimated_Gross_Profit"] = (
    monthly_sales["Total_Revenue"]
    - monthly_sales["Total_COGS"]
)

In [25]:
# Display results
display(monthly_sales.round(2))

C:\Users\Yaseen\AppData\Local\Temp\ipykernel_15380\3870188053.py:2: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  display(monthly_sales.round(2))

,Month,Sales_Records,Total_Revenue,Total_Quantity,Total_COGS,Estimated_Gross_Profit
0,2025-06,7864,753385.71,8182.0,398284.14,355101.57
1,2025-07,9573,909936.86,10095.0,491967.89,417968.97
2,2025-08,17688,1615531.95,18396.0,875152.73,740379.22
3,2025-09,9836,921709.59,10320.0,523225.12,398484.48
4,2025-10,9207,875543.70,9775.0,499937.64,375606.06
5,2025-11,9573,926493.24,10078.0,513875.79,412617.45
6,2025-12,18417,1921348.28,20110.0,1065501.70,855846.58
7,2026-01,7175,639690.80,7391.0,378652.15,261038.65
8,2026-02,10273,1111204.92,10899.0,601660.50,509544.42
9,2026-03,12201,999855.76,12588.0,593751.81,406103.95
10,2026-04,6453,540980.45,6708.0,313517.36,227463.09