In [11]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
print("Project Started")

Project Started

Step1:- create var project dir and store csv data path

In [13]:
PROJECT_DIR = Path(
    r"C:\Users\Yaseen\DA_DS\MINI_PROJECT\smart_data_analysis\data"
)

In [14]:
DATA_DIR = PROJECT_DIR

Step2:- create two more var sales and inventory or this var store csv file then print csv file

In [15]:
sales = pd.read_csv(DATA_DIR / "retail_sales_ml_apl.csv")

In [16]:
inventory = pd.read_csv(DATA_DIR / "retail_inventory_ml_apl.csv")

In [17]:
print("Sales Shape:", sales.shape)
print("Inventory Shape:", inventory.shape)

Sales Shape: (125751, 17)
Inventory Shape: (284755, 18)

In [18]:
display(sales.head())

,Transaction Date,Sales Type,Is Return,Reason of Return,Supplier,Product No,Product Description,Product Division,Product Category,Product Subcategory,Product Segment,Store,Sales Channel,Qty Sold,Sales Amount,Cogs,Number of Transactions
0,2025-09-01,Full Price,0,NaN,Vendor 0169,PROD-139867,PROD-100449 SEG-500065 Scholar Footwear Trailb...,Scholar Footwear,Scholar Footwear Trailblazer,Scholar Footwear Trailblazer Equilibrium,SEG-500065 Scholar Footwear Trailblazer Equili...,STR-1006,Channel Alpha,1.0,115.00,52.31,1
1,2025-09-07,Full Price,0,NaN,Vendor 0166,PROD-100449,PROD-100825 SEG-500112 Heritage Footwear Fligh...,Femme Footwear,Femme Footwear Flight Classic,Femme Footwear Flight Classic Varied,SEG-500112 Heritage Footwear Flight Classic Ze...,STR-1198,Channel Alpha,1.0,115.00,58.47,1
2,2025-08-06,Promo,0,NaN,Vendor 0169,PROD-153623,PROD-148813 SEG-511388 Scholar Footwear Trailb...,Scholar Footwear,Scholar Footwear Trailblazer,Scholar Footwear Trailblazer Equilibrium,SEG-511388 Scholar Footwear Trailblazer Equili...,STR-1157,Channel Alpha,1.0,79.99,43.76,1
3,2025-08-31,Full Price,0,NaN,Vendor 0246,PROD-140876,PROD-100419 SEG-500063 Scholar Footwear Boot C...,Scholar Footwear,Scholar Footwear Boot Collection,Scholar Footwear Boot Collection Woodland,SEG-500063 Scholar Footwear Boot Collection Wo...,STR-1234,Channel Alpha,1.0,110.00,50.60,1
4,2026-03-22,Full Price,0,NaN,Vendor 0169,PROD-166113,PROD-149345 SEG-511444 Femme Footwear Trailbla...,Femme Footwear,Femme Footwear Trailblazer,Femme Footwear Trailblazer Equilibrium,SEG-511444 Femme Footwear Trailblazer Equilibrium,STR-1157,Channel Alpha,1.0,160.00,77.95,1

In [19]:
display(inventory.head())

,Start Date,End Date,Stock Status,Supplier,Product No,Product Description,Product Division,Product Category,Product Subcategory,Product Segment,Store,Store Type,Sales Channel,Qty on hand,Stocks Selling Amount,Cost of Stocks,Stock Unit Selling Price,Stock Unit Cost Price
0,2025-08-07,2025-10-18,Full Price,Vendor 0255,PROD-159369,PROD-103395 SEG-500461 Scholar Footwear Canvas...,Scholar Footwear,Scholar Footwear Canvas Styles,Scholar Footwear Canvas Styles Drifter,SEG-500461 Scholar Footwear Canvas Styles Drifter,STR-1010,Retail Storefront,Channel Alpha,1,55.0,24.75,55.0,24.75
1,2026-02-15,2026-02-15,Full Price,Vendor 0010,PROD-180713,PROD-190644 SEG-520887 Femme Footwear Court Ca...,Femme Footwear,Femme Footwear Court Casual,Femme Footwear Court Casual Trident,SEG-520887 Femme Footwear Court Casual Trident,STR-1082,Retail Storefront,Channel Alpha,1,130.0,59.73,130.0,59.73
2,2026-01-08,2026-02-15,Full Price,Vendor 0166,PROD-169474,PROD-153439 SEG-512518 Femme Footwear Court Ca...,Femme Footwear,Femme Footwear Court Casual,Femme Footwear Court Casual Zephyr,SEG-512518 Femme Footwear Court Casual Zephyr,STR-1105,Retail Storefront,Channel Alpha,1,120.0,60.44,120.0,60.44
3,2025-12-23,2026-02-15,Full Price,Vendor 0106,PROD-170976,PROD-122029 SEG-504463 Junior Apparel Cozy Pul...,Junior Apparel,Junior Apparel Cozy Pullovers,Junior Apparel Cozy Pullovers Varied,SEG-504463 Junior Apparel Cozy Pullovers Varied,STR-1157,Retail Storefront,Channel Alpha,3,150.0,52.50,50.0,17.50
4,2026-02-10,9999-12-31,Full Price,Vendor 0134,PROD-183525,PROD-111954 SEG-502325 Scholar Footwear Modern...,Scholar Footwear,Scholar Footwear Modern Legend,Scholar Footwear Modern Legend Summit,SEG-502325 Scholar Footwear Modern Legend Summit,STR-1253,Retail Storefront,Channel Alpha,4,360.0,182.16,90.0,45.54

In [20]:
print(sales.info())
print(inventory.info())

<class 'pandas.DataFrame'>
RangeIndex: 125751 entries, 0 to 125750
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Transaction Date        125751 non-null  str
 1   Sales Type              125751 non-null  str
 2   Is Return               125751 non-null  int64
 3   Reason of Return        0 non-null       float64
 4   Supplier                125751 non-null  str
 5   Product No              125751 non-null  str
 6   Product Description     125751 non-null  str
 7   Product Division        125751 non-null  str
 8   Product Category        125751 non-null  str
 9   Product Subcategory     125751 non-null  str
 10  Product Segment         125751 non-null  str
 11  Store                   125751 non-null  str
 12  Sales Channel           125751 non-null  str
 13  Qty Sold                125751 non-null  float64
 14  Sales Amount            125751 non-null  float64
 15  Cogs                    125751 non-null  float64
 16  Number of Transactions  125751 non-null  int64
dtypes: float64(4), int64(2), str(11)
memory usage: 16.3 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 284755 entries, 0 to 284754
Data columns (total 18 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Start Date                284755 non-null  str
 1   End Date                  284755 non-null  str
 2   Stock Status              284755 non-null  str
 3   Supplier                  284755 non-null  str
 4   Product No                284755 non-null  str
 5   Product Description       284755 non-null  str
 6   Product Division          284755 non-null  str
 7   Product Category          284755 non-null  str
 8   Product Subcategory       284755 non-null  str
 9   Product Segment           284755 non-null  str
 10  Store                     284755 non-null  str
 11  Store Type                284755 non-null  str
 12  Sales Channel             284755 non-null  str
 13  Qty on hand               284755 non-null  int64
 14  Stocks Selling Amount     284755 non-null  float64
 15  Cost of Stocks            284755 non-null  float64
 16  Stock Unit Selling Price  284755 non-null  float64
 17  Stock Unit Cost Price     284755 non-null  float64
dtypes: float64(4), int64(1), str(13)
memory usage: 39.1 MB
None

Step4:-Data Audit (means analysis start karne se pehle data ki condition check karna.  
1)Data mein kitni rows aur columns hain?  
2)Koi information missing toh nahi?  
3)Koi records duplicate toh nahi?  
4)Dates aur numbers correct data types mein hain ya nahi?)

In [21]:
print("Shape:", sales.shape)

Shape: (125751, 17)

In [22]:
print(sales.isnull().sum())

Transaction Date               0
Sales Type                     0
Is Return                      0
Reason of Return          125751
Supplier                       0
Product No                     0
Product Description            0
Product Division               0
Product Category               0
Product Subcategory            0
Product Segment                0
Store                          0
Sales Channel                  0
Qty Sold                       0
Sales Amount                   0
Cogs                           0
Number of Transactions         0
dtype: int64

In [23]:
print("Duplicate rowa: ",sales.duplicated().sum())

Duplicate rowa:  0

Sales aur inventory alag business questions answer karte hain.  
sales	:-> Kaunsa product kitna sell hua aur kitna revenue aaya?  
inventory	:-> Kitna stock available hai aur uski value kitni hai?

In [24]:
print("\nINVENTORY MISSING VALUES")
print(inventory.isnull().sum())

INVENTORY MISSING VALUES
Start Date                  0
End Date                    0
Stock Status                0
Supplier                    0
Product No                  0
Product Description         0
Product Division            0
Product Category            0
Product Subcategory         0
Product Segment             0
Store                       0
Store Type                  0
Sales Channel               0
Qty on hand                 0
Stocks Selling Amount       0
Cost of Stocks              0
Stock Unit Selling Price    0
Stock Unit Cost Price       0
dtype: int64

In [25]:
print("\nINVENTORY DUPLICATES")
print(inventory.duplicated().sum())

INVENTORY DUPLICATES
0

Step 5 — Business data inspect karo  
Is step ka purpose hai dataset ke andar ka actual data dekhna, taaki humein pata chale ki values sensible hain ya nahi.

In [26]:
display(sales.sample(5, random_state=42))

,Transaction Date,Sales Type,Is Return,Reason of Return,Supplier,Product No,Product Description,Product Division,Product Category,Product Subcategory,Product Segment,Store,Sales Channel,Qty Sold,Sales Amount,Cogs,Number of Transactions
16615,2025-12-07,Promo,0,NaN,Vendor 0169,PROD-166166,PROD-148939 SEG-511404 Femme Footwear Trailbla...,Femme Footwear,Femme Footwear Trailblazer,Femme Footwear Trailblazer Equilibrium,SEG-511404 Femme Footwear Trailblazer Equilibrium,STR-1074,Channel Alpha,1.0,59.99,50.05,1
98454,2025-09-01,Full Price,0,NaN,Vendor 0166,PROD-168840,PROD-170351 SEG-516327 Junior Apparel Crew Tee...,Junior Apparel,Junior Apparel Crew Tees,Junior Apparel Crew Tees Varied,SEG-516327 Junior Apparel Crew Tees Varied,STR-1114,Channel Alpha,1.0,25.00,11.50,1
120727,2025-12-06,Full Price,0,NaN,Vendor 0258,PROD-184465,PROD-179900 SEG-518118 Scholar Footwear Trailb...,Scholar Footwear,Scholar Footwear Trailblazer,Scholar Footwear Trailblazer Swift Run,SEG-518118 Scholar Footwear Trailblazer Swift Run,STR-1344,Channel Alpha,1.0,49.50,43.56,1
45753,2025-06-30,Promo,0,NaN,Vendor 0010,PROD-157528,PROD-122574 SEG-504599 Femme Footwear Court Ca...,Femme Footwear,Femme Footwear Court Casual,Femme Footwear Court Casual Trident,SEG-504599 Femme Footwear Court Casual Trident,STR-1157,Channel Alpha,1.0,59.99,51.70,1
106261,2025-06-27,Full Price,0,NaN,Vendor 0166,PROD-161780,PROD-188025 SEG-520261 Femme Footwear Trailbla...,Femme Footwear,Femme Footwear Trailblazer,Femme Footwear Trailblazer Zephyr,SEG-520261 Femme Footwear Trailblazer Zephyr,STR-1148,Channel Alpha,1.0,90.00,45.04,1